name: text-to-image-item-generator_env
channels:
  - nvidia
  - pytorch
  - defaults
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - conda:
      - pytorch-cuda=11.8  # CUDA support from conda
      - cmake
  - pip:
      - transformers
      - diffusers
      - huggingface_hub
      - torch==2.6.0
      - torchvision==0.21.0
      - torchaudio==2.6.0
      - accelerate
      - sentencepiece
      - protobuf
      - --extra-index-url https://download.pytorch.org/whl/cu118  # Add PyTorch custom index URL for CUDA 11.8
